# -*- coding: utf-8 -*-
"""Naive_bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1om4t9LYgv9KBqDtDlbT0HkX_et267ONT

**Naive Bayes** algorithm using Iris dataset

---
"""

from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

df = datasets.load_iris()

X = df.data
y = df.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = GaussianNB()
model.fit(X_train, y_train)
model.score(X_test, y_test)

expected = y_test
predicted = model.predict(X_test)
print(expected)
print(predicted)

print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

